- Name: CheckAndNavigateAsync
  Asynchronous: true
  Code: |
    if(await Methods.CheckAsync(uiViewName))
    {
        NavigateAsync
        (
            new NavigationOptions(uiViewName)
                .WithContainerId(Fields.ContainerId)
        );
    }
- Name: CheckAsync
  Asynchronous: true
  Code: |-
    var viewModel = FindViewModelOfViewContainer<GroupeIsa.Neos.Application.UI.IUIView>(Fields.ContainerId);

    if (viewModel == null)
    {
        return true;
    }

    if (viewModel.UIViewName == uiViewName || viewModel.HasErrors)
    {
        if (viewModel.HasErrors)
        {
            this.ShowToast(MessageType.Danger, Resources.Core.SaveErrorTitle, string.Empty);
        }

        return false;
    }

    if (!viewModel.HasChanges)
    {
        return true;
    }

    await viewModel.CloseAsync();

    return !viewModel.HasErrors;
  DotNetReturnType: bool
