Template: |-
  <template-setting title="@Title" icon="@Icon">
      <left-panel>
          <button type="action" action-name="UserAccount" />
          <button type="action" action-name="AssignPermission" />
          <button type="action" action-name="GroupPoker" />
      </left-panel>
      <right-panel>
          <view-container container-id="UserAndRightSettingsContainerId" layout:height="fill" />
      </right-panel>
  </template-setting>
