- Name: GroupPoker
  Caption: Groupe des pokers
  Code: Methods.CheckAndNavigateAsync("GroupeListUi");
- Name: AssignPermission
  Caption: Roles and permissions
  Code: Methods.CheckAndNavigateAsync("AssignPermissionToRolesUI");
  Location: Hidden
  Style: Ghost
- Name: UserAccount
  Caption: Users
  Code: Methods.CheckAndNavigateAsync("UserAccountListUI");
  Location: Hidden
  Style: Ghost
