# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

#env:
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
          dotnet-version: 7
          
    - name: Install Nuget source
      run: dotnet nuget add source "https://pkgs.dev.azure.com/POLE-ERP-GROUPEISA/Neos-Public/_packaging/Neos-Public/nuget/v3/index.json" -n "Neos-Public"
    - name: Install Neos
      run: dotnet tool install GroupeIsa.Neos.Console --global --ignore-failed-sources --no-cache --interactive --verbosity minimal
    - name: Neos Generate
      run: neos generate
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.3
      with:
        script: |
          "env | sort"
